// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dr_viki.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNlh_20GxdMlqSTr_3UsaBOs_Zt61KEoc',
    appId: '1:472330705050:web:a6ca636e8306c0c755e723',
    messagingSenderId: '472330705050',
    projectId: 'dr-viki-app',
    authDomain: 'dr-viki-app.firebaseapp.com',
    storageBucket: 'dr-viki-app.firebasestorage.app',
    measurementId: 'G-4S7ZXCQ413',
    databaseURL: 'https://dr-viki-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMmkHO9vGpd8palD_gOaDSWLzgJnb0pU',
    appId: '1:472330705050:android:61314c7e9400e52155e723',
    messagingSenderId: '472330705050',
    projectId: 'dr-viki-app',
    storageBucket: 'dr-viki-app.firebasestorage.app',
    databaseURL: 'https://dr-viki-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz7dqMAgB_be_SJQ6qcvCA6huyLcwOa98',
    appId: '1:472330705050:ios:9bf89e0c32f78f7455e723',
    messagingSenderId: '472330705050',
    projectId: 'dr-viki-app',
    storageBucket: 'dr-viki-app.firebasestorage.app',
    iosBundleId: 'com.drviki.app',
    databaseURL: 'https://dr-viki-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz7dqMAgB_be_SJQ6qcvCA6huyLcwOa98',
    appId: '1:472330705050:ios:9bf89e0c32f78f7455e723',
    messagingSenderId: '472330705050',
    projectId: 'dr-viki-app',
    storageBucket: 'dr-viki-app.firebasestorage.app',
    iosBundleId: 'com.drviki.app',
    databaseURL: 'https://dr-viki-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRMmkHO9vGpd8palD_gOaDSWLzgJnb0pU',
    appId: '1:472330705050:web:61314c7e9400e52155e723',
    messagingSenderId: '472330705050',
    projectId: 'dr-viki-app',
    authDomain: 'dr-viki-app.firebaseapp.com',
    storageBucket: 'dr-viki-app.firebasestorage.app',
    measurementId: 'G-4S7ZXCQ413',
    databaseURL: 'https://dr-viki-app-default-rtdb.firebaseio.com',
  );
} 